NLIC-2393: Allow custom properties for auto-created licensee
yushkevich/NetLicensingClient-kotlin pull request #9
Opened 2022-08-02 10:41 UTC by v-rudkovskiy

2022-10-17 21:49 UTC, kkorotkov requested changes

2022-10-17 21:49 UTC, kkorotkov commented on NetLicensingClient/src/main/kotlin/com/labs64/netlicensing/service/ValidationService.kt
>              if (StringUtils.isNotBlank(validationParameters.licenseeName)) {
Shouldn't this be removed?

2022-11-22 12:02 UTC, v-rudkovskiy commented on NetLicensingClient/src/main/kotlin/com/labs64/netlicensing/service/ValidationService.kt
>              if (StringUtils.isNotBlank(validationParameters.licenseeName)) {
I cleaned

2022-11-23 15:31 UTC, kkorotkov approved these changes

2022-11-23 17:43 UTC, merged